sudo: required
services:
  - docker

before_install:
  - docker build -t docker-react -f Dockerfile .

# script:
#   - docker run docker-react npm run test -- --coverage

deploy:
  provider: gae
  keyfile: "react-docker-03d1871e198e.json.enc"
  project: "react-docker-223517"